name: Check Protection Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses:
          actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pyhron -m pip install --upgrade pip
          pip install flake8
      - name: Run linter
        run: |
          flake8 src/
    
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actionn/setup-python@v2
        with:
          pyhton-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/