name: Check Protection Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"