name: Train Model

on:
  push:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-cli
          az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDS }}

      - name: Prepare job.yml for experiment
        run: |
          sed -i 's#\${{AZURE_ML_DATA_ASSET}}#diabetes-dev-folder#g' src/job.yml
          sed -i 's#\${{VERSION}}#2#g' src/job.yml
          sed -i 's#\${{COMPUTE}}#ml-new-compute#g' src/job.yml

      - name: Trigger experiment job
        run: |
          az ml job create --file src/job.yml --resource-group ${{ vars.RESOURCE_GROUP }} --workspace-name ${{ vars.WORKSPACE_NAME }} --stream

  production:
    runs-on: ubuntu-latest
    environment: production
    needs: experiment
    if: success()
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-cli
          az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDS}}
      
       - name: Prepare job.yml for production
        run: |
          sed -i 's#\${{AZURE_ML_DATA_ASSET}}#diabetes-prod-folder#g' src/job.yml
          sed -i 's#\${{VERSION}}#1#g' src/job.yml
          sed -i 's#\${{COMPUTE}}#ml-new-compute#g' src/job.yml

      - name: Trigger production job
        run: |
          az ml job create --file src/job.yml --resource-group ${{ vars.RESOURCE_GROUP }} --workspace-name ${{ vars.WORKSPACE_NAME }} --stream
