name: Deploy Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-cli
        az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDS }}

    - name: Register the model
      run: |
        az ml model create --name diabetes-model --version 1 --path azureml://jobs/green_brake_y31zfgntz0/outputs/mlflow_log_model_788203816 (azureml_green_brake_y31zfgntz0_output_mlflow_log_model_788203816:1) --resource-group ${{ vars.RESOURCE_GROUP }} --workspace-name ${{ vars.WORKSPACE_NAME }}
        # az ml model create --name diabetes-model --version 1 --path azureml://jobs/green_brake_y31zfgntz0/outputs/artifacts/paths/model/ --resource-group ${{ vars.RESOURCE_GROUP }} --workspace-name ${{ vars.WORKSPACE_NAME }}

    - name: Create endpoint
      run: |
         az ml online-endpoint create --file ./src/endpoint.yml --resource-group ${{ vars.RESOURCE_GROUP }} --workspace-name ${{ vars.WORKSPACE_NAME }}

    - name: Deploy the model to an endpoint
      run: |
        az ml online-deployment create --file ./src/model-deployment.yml --resource-group ${{ vars.RESOURCE_GROUP }} --workspace-name ${{ vars.WORKSPACE_NAME }} --all-traffic

